08_frameworks/Django/agenda/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login, name='index_login'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

08_frameworks/Django/agenda/agenda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('contatos.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

08_frameworks/Django/agenda/contatos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:pk>', views.contato, name='contato'),
    path('busca/', views.busca, name='busca'),
]

08_frameworks/Django/agenda/accounts/models.py
from django.db import models
from contatos.models import Contato
from django import forms

# Create your models here.
class FormContato(forms.ModelForm):
    class Meta:
        model = Contato
        exclude = ()

08_frameworks/Django/agenda/contatos/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Categoria(models.Model):
    nome = models.CharField(max_length=255)

    def __str__(self):
        return self.nome

class Contato(models.Model):
    nome = models.CharField(max_length=255)
    sobrenome = models.CharField(max_length=255, blank=True)
    telefone = models.CharField(max_length=255, blank=True)
    email = models.CharField(max_length=255, blank=True)
    data_criacao = models.DateTimeField(auto_now_add=False, default=datetime.now)
    descricao = models.TextField(blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    exibir = models.BooleanField(default=True)
    foto = models.ImageField(blank=True, upload_to='fotos/%Y/%m/')
    
    def __str__(self):
        return self.nome

08_frameworks/Django/agenda/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.core.validators import validate_email
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import FormContato

# Create your views here.
def login(request):
    if request.method != 'POST':
        return render(request, 'login/login.html')

    usuario = request.POST.get('usuario')
    senha = request.POST.get('senha')

    user = auth.authenticate(request, username=usuario, password=senha)

    if not user:
        messages.error(request, 'Usuário ou senha inválidos.')
        return render(request, 'login/login.html')
    else:
        auth.login(request, user)
        messages.success(request, 'Você fez login com sucesso')
        return redirect('accounts:dashboard')

def logout(request):
    auth.logout(request)
    return redirect('accounts:login')

def cadastro(request):
    if request.method != 'POST':
        return render(request, 'login/cadastro.html')

    nome = request.POST.get('nome')
    sobrenome = request.POST.get('sobrenome')
    email = request.POST.get('email')
    usuario = request.POST.get('usuario')
    senha = request.POST.get('senha')
    valida_senha = request.POST.get('valida_senha')

    # Validações    
    if not nome or not sobrenome or not email or not senha \
        or not valida_senha:
        messages.error(request, 'Nenhum campo pode estar vazio.')
        return render(request, 'login/cadastro.html')

    try:
        validate_email(email)
    except:
        messages.error(request, 'E-mail inválido.')
        return render(request, 'login/cadastro.html')

    if len(senha) < 6 or len(usuario) < 6:
        messages.error(request, 'Usuário e senha e  precisam ter no mínimo 6 caracteres.')
        return render(request, 'login/cadastro.html')

    if senha != valida_senha:
        messages.error(request, 'Senhas não conferem.')
        return render(request, 'login/cadastro.html')

    if User.objects.filter(username=usuario).exists():
        messages.error(request, 'Usuário já existe.')
        return render(request, 'login/cadastro.html')

    if User.objects.filter(email=email).exists():
        messages.error(request, 'E-mail já existe.')
        return render(request, 'login/cadastro.html')
        
    # Registro
    user = User.objects.create_user(
        username=usuario,
        first_name=nome,
        last_name=sobrenome,
        email=email,
        password=senha
    )
    user.save()

    messages.success(request, 'Usuário registrado com sucesso!\n Agora faça login.')
    return redirect('accounts:login')

@login_required(redirect_field_name='accounts:login')
def dashboard(request):
    if request.method != 'POST':
        form = FormContato()
        return render(request, 'login/dashboard.html', {'form': form})

    form = FormContato(request.POST, request.FILES)

    if not form.is_valid():
        messages.error(request, 'Erro ao enviar formulário.')

        form = FormContato(request.POST)
        return render(request, 'login/dashboard.html', {'form': form})

    descricao = request.POST.get('descricao')

    if len(descricao) < 5:
        messages.error(request, 'Descrição precisa ter no mínimo 5 caracteres.')

        form = FormContato(request.POST)
        return render(request, 'login/dashboard.html', {'form': form})

    form.save()
    messages.success(request, f'Contato {request.POST.get("nome")} salvo com sucesso!')

    return redirect('accounts:dashboard')

08_frameworks/Django/agenda/contatos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.http import Http404
from .models import Contato, Categoria

from django.db.models import Q, Value
from django.db.models.functions import Concat

from django.contrib import messages

# Create your views here.
def home(request):
    # messages.add_message(request, messages.ERROR, 'Ocorreu um erro!')

    contatos = Contato.objects.all().order_by('nome').filter(exibir=True)
    paginator = Paginator(contatos, 5)

    page = request.GET.get('page')
    contatos = paginator.get_page(page)

    return render(request, 'contatos/home.html', {'contatos': contatos})

def contato(request, pk):
    contato = get_object_or_404(Contato, id=pk)

    if not contato.exibir:
        raise Http404

    return render(request, 'contatos/contato.html', {'contato': contato})
    
    """ Tratando error 404
    try:
        pass
    except Contato.DoesNotExist as e:
        raise Http404
    """

def busca(request):
    termo = request.GET.get('termo')
    campos = Concat('nome', Value(' '), 'sobrenome')
    
    if termo is None or not termo:
        messages.add_message(request, messages.ERROR, 'Campo termo não pode ficar vazio.')
        return redirect('home')

    contatos = Contato.objects.annotate(
        nome_completo=campos
    ).filter(
        Q(nome_completo__icontains=termo) | Q(telefone__icontains=termo)
    ).order_by('nome')

    paginator = Paginator(contatos, 5)

    page = request.GET.get('page')
    contatos = paginator.get_page(page)

    return render(request, 'contatos/home.html', {'contatos': contatos})

08_frameworks/Django/agenda/accounts/templates/login/cadastro.html
{% extends 'base.html' %}
{% block titulo %}Cadastro{% endblock %}

{% load static %}

{% block conteudo %}
<h1 class="m-3">Cadastro</h1>

<form method="POST" action="{% url 'accounts:cadastro' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" class="form-control" id="nome" name="nome" value="{{ request.POST.nome }}">
    </div>
    <div class="form-group">
        <label for="sobrenome">Sobrenome</label>
        <input type="text" class="form-control" id="sobrenome" name="sobrenome" value="{{ request.POST.sobrenome }}">
    </div>
    <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" class="form-control" id="email" name="email" value="{{ request.POST.email }}">
    </div>

    <div class="form-group">
        <label for="usuario">Usuário</label>
        <input type="text" class="form-control" id="usuario" name="usuario" value="{{ request.POST.usuario }}">
    </div>

    <div class="form-group">
        <label for="senha">Password</label>
        <input type="password" class="form-control" id="senha" name="senha">
    </div>
    <div class="form-group">
        <label for="valida_senha">Repetir senha</label>
        <input type="password" class="form-control" id="valida_senha" name="valida_senha">
    </div>

    <button type="submit" class="btn btn-primary">Cadastrar-me</button>
</form>
{% endblock %}

08_frameworks/Django/agenda/accounts/templates/login/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Dashboard{% endblock %}

{% block conteudo %}
<h1 class="m-3">Olá {{ user.first_name }} {{ user.last_name }}</h1>

<div class="container">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">
            {{ form }}
            <tr>
                <td>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

08_frameworks/Django/agenda/accounts/templates/login/login.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Login{% endblock %}

{% block conteudo %}
{% if not user.is_authenticated %} 
<h1 class="m-3">Login</h1>

<form method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="usuario">Usuário</label>
        <input type="text" class="form-control" id="usuario" name="usuario" value="{{ request.POST.usuario }}">
    </div>
    <div class="form-group">
        <label for="senha">Password</label>
        <input type="password" class="form-control" id="senha" name="senha">
    </div>

    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% else %}
<div class="m-3">
    <a href="{% url 'accounts:dashboard' %}">Ir para dashboard</a>
</div>
{% endif %}
{% endblock %}

08_frameworks/Django/agenda/contatos/templates/contatos/contato.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}{{ user.first_name }} {{ user.last_name }}{% endblock %}

{% block conteudo %}
<h1 class="mt-5">{{ contato.nome }} {{ contato.sobrenome }}</h1>

{% if contato.foto %}
<p>
    <img class="img-thumbnail" src="{{ contato.foto.url }}" width="128">
</p>
{% endif %}

<dl>
    <dt>ID</dt>
    <dd>{{ contato.id|safe }}</dd>

    <dt>{{ contato.nome }}</dt>
    <dd></dd>

    <dt>E-mail</dt>
    <dd>{{ contato.email }}</dd>

    <dt>Data criação</dt>
    <dd>{{ contato.data_criacao|date:'d/m/Y H:i:s' }}</dd>

    <dt>Categoria</dt>
    <dd>{{ contato.categoria }}</dd>

    <dt>Descrição</dt>
    <dd>
        {{ contato.descricao|safe }}
    </dd>
</dl>
{% endblock %}

08_frameworks/Django/agenda/contatos/templates/contatos/home.html
{% extends 'base.html' %}
{% load static %}

{% block conteudo %}
<h1 class="mt-5">Minha agenda</h1>

<br>

<form method="get" action="{% url 'busca' %}">
    <div class="form-group row">
        <div class="col-12">
            <input
                class="form-control"
                type="search"
                value="{{ request.GET.termo }}"
                id="search-input"
                placeholder="Digite sua pesquisa"
                name="termo"
            />
        </div>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>id</th>
            <th>Nome</th>
            <th>Sobrenome</th>
            <th>Telefone</th>
            <th>Categoria</th>
        </tr>
    </thead>
    <tbody>

        
    {% for contato in contatos %}
        {% if contato.exibir %}
        <tr>
            <td>{{ contato.id|safe }}</td>
            <td>
                <a href="{% url 'contato' contato.id %}">{{ contato.nome }}</a>
            </td>
            <td>{{ contato.sobrenome }}</td>
            <td>{{ contato.telefone }}</td>
            <td>{{ contato.categoria }}</td>
        </tr>
        {% endif %}
    {% endfor %}
    
    </tbody>
</table>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% for pagina in contatos.paginator.page_range %}
            <li class="page-item {% if contatos.number == pagina %}active{% endif %}">
                <a class="page-link" href="?page={{ pagina }}&termo={{ request.GET.termo }}">{{ pagina }}</a>
            </li>
        {% endfor %}
    </ul>
</nav>
{% endblock %}

08_frameworks/Django/agenda/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
    <head>
        <title>{% block titulo %}Agenda{% endblock %}</title>
        {% include 'parciais/head.html' %}
    </head>
    
    <body>
        <!-- Navigation -->
        {% include 'parciais/nav.html' %}

        <!-- Messages -->
        {% include 'parciais/messages.html' %}

        <!-- Page Content -->
        <div class="container">
            <div class="row">
                <div class="col-lg-12">{% block conteudo %}{% endblock %}</div>
            </div>
        </div>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'jquery/jquery.slim.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

08_frameworks/Django/agenda/templates/parciais/head.html
{% load static %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
<meta name="description" content="" />
<meta name="author" content="" />

<!-- Bootstrap core CSS -->
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />

08_frameworks/Django/agenda/templates/parciais/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

08_frameworks/Django/agenda/templates/parciais/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="#">Agenda</a>
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarResponsive"
            aria-controls="navbarResponsive"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>