08_frameworks/Django/projeto/paginas/urls.py
from django.urls import path
from . import views

app_name = 'paginas'

urlpatterns = [
    path('', views.index, name='index'),
    path('sobre/', views.sobre, name='sobre'),
]

08_frameworks/Django/projeto/projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('paginas.urls')),
    path('admin/', admin.site.urls),
]

08_frameworks/Django/projeto/paginas/models.py
from django.db import models

# Create your models here.

08_frameworks/Django/projeto/paginas/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'paginas/index.html')

def sobre(request):
    return render(request, 'paginas/sobre.html')

08_frameworks/Django/projeto/paginas/templates/paginas/index.html
{% extends 'base.html' %}

{% block conteudo %}
    teste
{% endblock %}

08_frameworks/Django/projeto/paginas/templates/paginas/sobre.html
{% extends 'base.html' %}
{% load static %}

{% block conteudo %}
    <h1>Sobre</h1>

    <img class="img-fluid" src="{% static 'img/a.jpg' %}">
{% endblock %}

08_frameworks/Django/projeto/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
    {% include 'parciais/head.html' %}

    <body>
        <!-- Navigation -->
        {% include 'parciais/nav.html' %}

        <!-- Page Content -->
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    {% block conteudo %}{% endblock %}
                </div>
            </div>
        </div>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'paginas/vendor/jquery/jquery.slim.min.js' %}"></script>
        <script src="{% static 'paginas/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

08_frameworks/Django/projeto/templates/parciais/head.html
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Template Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
</head>

08_frameworks/Django/projeto/templates/parciais/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="#">Template</a>
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarResponsive"
            aria-controls="navbarResponsive"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'paginas:index' %}">
                      Home <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'paginas:sobre' %}">Sobre</a>
                </li>
            </ul>
        </div>
    </div>
</nav>